# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request
from . import agent_pb2 as m
import asyncio

class AgentServiceClient:
    def __init__(self, transport: Transport): self._t = transport

    async def health(self, req: m.HealthRequest) -> m.HealthResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Health", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.HealthResponse.FromString(res.body)

    async def listSessions(self, req: m.ListSessionsRequest) -> m.ListSessionsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListSessions", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListSessionsResponse.FromString(res.body)

    async def createSession(self, req: m.CreateSessionRequest) -> m.CreateSessionResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/CreateSession", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.CreateSessionResponse.FromString(res.body)

    async def getSession(self, req: m.GetSessionRequest) -> m.GetSessionResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetSession", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetSessionResponse.FromString(res.body)

    async def deleteSession(self, req: m.DeleteSessionRequest) -> m.DeleteSessionResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeleteSession", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.DeleteSessionResponse.FromString(res.body)

    async def listMessages(self, req: m.ListMessagesRequest) -> m.ListMessagesResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListMessages", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListMessagesResponse.FromString(res.body)

    async def prompt(self, req: m.PromptRequest) -> "AsyncIterator[m.PromptResponse]":
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/Prompt", body=req.SerializeToString()))
        async for chunk in st: yield m.PromptResponse.FromString(chunk)

    async def watchSession(self, req: m.WatchSessionRequest) -> "AsyncIterator[m.WatchSessionResponse]":
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/WatchSession", body=req.SerializeToString()))
        async for chunk in st: yield m.WatchSessionResponse.FromString(chunk)

    async def watchSessions(self, req: m.WatchSessionsRequest) -> "AsyncIterator[m.WatchSessionsResponse]":
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/WatchSessions", body=req.SerializeToString()))
        async for chunk in st: yield m.WatchSessionsResponse.FromString(chunk)

    async def fork(self, req: m.ForkRequest) -> m.ForkResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Fork", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ForkResponse.FromString(res.body)

    async def rename(self, req: m.RenameRequest) -> m.RenameResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Rename", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.RenameResponse.FromString(res.body)

    async def setModel(self, req: m.SetModelRequest) -> m.SetModelResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetModel", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.SetModelResponse.FromString(res.body)

    async def undo(self, req: m.UndoRequest) -> m.UndoResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Undo", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.UndoResponse.FromString(res.body)

    async def state(self, req: m.StateRequest) -> m.StateResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/State", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.StateResponse.FromString(res.body)

    async def mailbox(self, req: m.MailboxRequest) -> m.MailboxResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Mailbox", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.MailboxResponse.FromString(res.body)

    async def updateSettings(self, req: m.UpdateSettingsRequest) -> m.UpdateSettingsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/UpdateSettings", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.UpdateSettingsResponse.FromString(res.body)

    async def interrupt(self, req: m.InterruptRequest) -> m.InterruptResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Interrupt", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.InterruptResponse.FromString(res.body)

    async def compact(self, req: m.CompactRequest) -> m.CompactResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/Compact", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.CompactResponse.FromString(res.body)

    async def listProviders(self, req: m.ListProvidersRequest) -> m.ListProvidersResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListProviders", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListProvidersResponse.FromString(res.body)

    async def listProvidersCatalog(self, req: m.ListProvidersCatalogRequest) -> m.ListProvidersCatalogResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListProvidersCatalog", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListProvidersCatalogResponse.FromString(res.body)

    async def registerProvider(self, req: m.RegisterProviderRequest) -> m.RegisterProviderResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/RegisterProvider", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.RegisterProviderResponse.FromString(res.body)

    async def discoverGatewayModels(self, req: m.DiscoverGatewayModelsRequest) -> m.DiscoverGatewayModelsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/DiscoverGatewayModels", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.DiscoverGatewayModelsResponse.FromString(res.body)

    async def deleteProvider(self, req: m.DeleteProviderRequest) -> m.DeleteProviderResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeleteProvider", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.DeleteProviderResponse.FromString(res.body)

    async def testProvider(self, req: m.TestProviderRequest) -> m.TestProviderResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/TestProvider", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.TestProviderResponse.FromString(res.body)

    async def listModels(self, req: m.ListModelsRequest) -> m.ListModelsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListModels", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListModelsResponse.FromString(res.body)

    async def listPresets(self, req: m.ListPresetsRequest) -> m.ListPresetsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListPresets", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListPresetsResponse.FromString(res.body)

    async def upsertPreset(self, req: m.UpsertPresetRequest) -> m.UpsertPresetResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/UpsertPreset", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.UpsertPresetResponse.FromString(res.body)

    async def deletePreset(self, req: m.DeletePresetRequest) -> m.DeletePresetResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeletePreset", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.DeletePresetResponse.FromString(res.body)

    async def previewPreset(self, req: m.PreviewPresetRequest) -> m.PreviewPresetResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/PreviewPreset", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.PreviewPresetResponse.FromString(res.body)

    async def getConfig(self, req: m.GetConfigRequest) -> m.GetConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetConfigResponse.FromString(res.body)

    async def setConfig(self, req: m.SetConfigRequest) -> m.SetConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.SetConfigResponse.FromString(res.body)

    async def listTools(self, req: m.ListToolsRequest) -> m.ListToolsResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListTools", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListToolsResponse.FromString(res.body)

    async def getToolConfig(self, req: m.GetToolConfigRequest) -> m.GetToolConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetToolConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetToolConfigResponse.FromString(res.body)

    async def setToolConfig(self, req: m.SetToolConfigRequest) -> m.SetToolConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetToolConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.SetToolConfigResponse.FromString(res.body)

    async def setExtensionConfig(self, req: m.SetExtensionConfigRequest) -> m.SetExtensionConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetExtensionConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.SetExtensionConfigResponse.FromString(res.body)

    async def uploadFile(self, req: m.UploadFileRequest) -> m.UploadFileResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/UploadFile", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.UploadFileResponse.FromString(res.body)

    async def ingestFile(self, req: m.IngestFileRequest) -> m.IngestFileResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/IngestFile", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.IngestFileResponse.FromString(res.body)

    async def getFile(self, req: m.GetFileRequest) -> m.GetFileResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetFile", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetFileResponse.FromString(res.body)

    async def getFileMeta(self, req: m.GetFileMetaRequest) -> m.GetFileMetaResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetFileMeta", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetFileMetaResponse.FromString(res.body)

    async def getAgentConfig(self, req: m.GetAgentConfigRequest) -> m.GetAgentConfigResponse:
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetAgentConfig", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.GetAgentConfigResponse.FromString(res.body)
