# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request
from . import agent_pb2 as m
import asyncio

class AdminServiceClient:
    def __init__(self, transport: Transport): self._t = transport

    async def listTenants(self, req: m.ListTenantsRequest) -> m.ListTenantsResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/ListTenants", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListTenantsResponse.FromString(res.body)

    async def createTenant(self, req: m.CreateTenantRequest) -> m.CreateTenantResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/CreateTenant", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.CreateTenantResponse.FromString(res.body)

    async def updateTenant(self, req: m.UpdateTenantRequest) -> m.UpdateTenantResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/UpdateTenant", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.UpdateTenantResponse.FromString(res.body)

    async def deleteTenant(self, req: m.DeleteTenantRequest) -> m.DeleteTenantResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/DeleteTenant", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.DeleteTenantResponse.FromString(res.body)

    async def issueTenantToken(self, req: m.IssueTenantTokenRequest) -> m.IssueTenantTokenResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/IssueTenantToken", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.IssueTenantTokenResponse.FromString(res.body)

    async def listTenantTokens(self, req: m.ListTenantTokensRequest) -> m.ListTenantTokensResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/ListTenantTokens", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.ListTenantTokensResponse.FromString(res.body)

    async def revokeTenantToken(self, req: m.RevokeTenantTokenRequest) -> m.RevokeTenantTokenResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/RevokeTenantToken", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.RevokeTenantTokenResponse.FromString(res.body)

    async def rotateTenantToken(self, req: m.RotateTenantTokenRequest) -> m.RotateTenantTokenResponse:
        res = await self._t.send(Request(url="/agent.v1.AdminService/RotateTenantToken", body=req.SerializeToString()))
        if res.error: raise res.error
        return m.RotateTenantTokenResponse.FromString(res.body)
