# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for
from . import agent_pb2 as m
import asyncio

class AgentServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def health(self, req: m.HealthRequest, kind: str = "proto") -> m.HealthResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Health", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.HealthResponse, kind)

    async def getIdentity(self, req: m.GetIdentityRequest, kind: str = "proto") -> m.GetIdentityResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetIdentity", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetIdentityResponse, kind)

    async def listSessions(self, req: m.ListSessionsRequest, kind: str = "proto") -> m.ListSessionsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListSessions", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListSessionsResponse, kind)

    async def createSession(self, req: m.CreateSessionRequest, kind: str = "proto") -> m.CreateSessionResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/CreateSession", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.CreateSessionResponse, kind)

    async def getSession(self, req: m.GetSessionRequest, kind: str = "proto") -> m.GetSessionResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetSession", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetSessionResponse, kind)

    async def deleteSession(self, req: m.DeleteSessionRequest, kind: str = "proto") -> m.DeleteSessionResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeleteSession", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.DeleteSessionResponse, kind)

    async def listMessages(self, req: m.ListMessagesRequest, kind: str = "proto") -> m.ListMessagesResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListMessages", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListMessagesResponse, kind)

    async def prompt(self, req: m.PromptRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/Prompt", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.PromptResponse, kind))

    async def watchSession(self, req: m.WatchSessionRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/WatchSession", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.WatchSessionResponse, kind))

    async def watchSessions(self, req: m.WatchSessionsRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/WatchSessions", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.WatchSessionsResponse, kind))

    async def fork(self, req: m.ForkRequest, kind: str = "proto") -> m.ForkResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Fork", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ForkResponse, kind)

    async def rename(self, req: m.RenameRequest, kind: str = "proto") -> m.RenameResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Rename", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.RenameResponse, kind)

    async def setModel(self, req: m.SetModelRequest, kind: str = "proto") -> m.SetModelResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetModel", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.SetModelResponse, kind)

    async def undo(self, req: m.UndoRequest, kind: str = "proto") -> m.UndoResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Undo", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.UndoResponse, kind)

    async def state(self, req: m.StateRequest, kind: str = "proto") -> m.StateResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/State", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.StateResponse, kind)

    async def mailbox(self, req: m.MailboxRequest, kind: str = "proto") -> m.MailboxResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Mailbox", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.MailboxResponse, kind)

    async def updateSettings(self, req: m.UpdateSettingsRequest, kind: str = "proto") -> m.UpdateSettingsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/UpdateSettings", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.UpdateSettingsResponse, kind)

    async def interrupt(self, req: m.InterruptRequest, kind: str = "proto") -> m.InterruptResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Interrupt", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.InterruptResponse, kind)

    async def compact(self, req: m.CompactRequest, kind: str = "proto") -> m.CompactResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/Compact", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.CompactResponse, kind)

    async def listProviders(self, req: m.ListProvidersRequest, kind: str = "proto") -> m.ListProvidersResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListProviders", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListProvidersResponse, kind)

    async def listProvidersCatalog(self, req: m.ListProvidersCatalogRequest, kind: str = "proto") -> m.ListProvidersCatalogResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListProvidersCatalog", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListProvidersCatalogResponse, kind)

    async def registerProvider(self, req: m.RegisterProviderRequest, kind: str = "proto") -> m.RegisterProviderResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/RegisterProvider", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.RegisterProviderResponse, kind)

    async def deleteProvider(self, req: m.DeleteProviderRequest, kind: str = "proto") -> m.DeleteProviderResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeleteProvider", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.DeleteProviderResponse, kind)

    async def testProvider(self, req: m.TestProviderRequest, kind: str = "proto") -> m.TestProviderResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/TestProvider", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.TestProviderResponse, kind)

    async def listModels(self, req: m.ListModelsRequest, kind: str = "proto") -> m.ListModelsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListModels", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListModelsResponse, kind)

    async def listPresets(self, req: m.ListPresetsRequest, kind: str = "proto") -> m.ListPresetsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListPresets", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListPresetsResponse, kind)

    async def upsertPreset(self, req: m.UpsertPresetRequest, kind: str = "proto") -> m.UpsertPresetResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/UpsertPreset", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.UpsertPresetResponse, kind)

    async def deletePreset(self, req: m.DeletePresetRequest, kind: str = "proto") -> m.DeletePresetResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/DeletePreset", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.DeletePresetResponse, kind)

    async def previewPreset(self, req: m.PreviewPresetRequest, kind: str = "proto") -> m.PreviewPresetResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/PreviewPreset", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.PreviewPresetResponse, kind)

    async def getConfig(self, req: m.GetConfigRequest, kind: str = "proto") -> m.GetConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetConfigResponse, kind)

    async def setConfig(self, req: m.SetConfigRequest, kind: str = "proto") -> m.SetConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.SetConfigResponse, kind)

    async def listTools(self, req: m.ListToolsRequest, kind: str = "proto") -> m.ListToolsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/ListTools", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListToolsResponse, kind)

    async def getToolConfig(self, req: m.GetToolConfigRequest, kind: str = "proto") -> m.GetToolConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetToolConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetToolConfigResponse, kind)

    async def setToolConfig(self, req: m.SetToolConfigRequest, kind: str = "proto") -> m.SetToolConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetToolConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.SetToolConfigResponse, kind)

    async def setExtensionConfig(self, req: m.SetExtensionConfigRequest, kind: str = "proto") -> m.SetExtensionConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/SetExtensionConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.SetExtensionConfigResponse, kind)

    async def uploadFile(self, req: m.UploadFileRequest, kind: str = "proto") -> m.UploadFileResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/UploadFile", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.UploadFileResponse, kind)

    async def ingestFile(self, req: m.IngestFileRequest, kind: str = "proto") -> m.IngestFileResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/IngestFile", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.IngestFileResponse, kind)

    async def getFile(self, req: m.GetFileRequest, kind: str = "proto") -> m.GetFileResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetFile", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetFileResponse, kind)

    async def getFileMeta(self, req: m.GetFileMetaRequest, kind: str = "proto") -> m.GetFileMetaResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetFileMeta", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetFileMetaResponse, kind)

    async def getFileStream(self, req: m.GetFileRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/agent.v1.AgentService/GetFileStream", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.FileChunk, kind))

    async def getAgentConfig(self, req: m.GetAgentConfigRequest, kind: str = "proto") -> m.GetAgentConfigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AgentService/GetAgentConfig", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetAgentConfigResponse, kind)
