# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for
from . import agent_pb2 as m
import asyncio

class AdminServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def listTenants(self, req: m.ListTenantsRequest, kind: str = "proto") -> m.ListTenantsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/ListTenants", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListTenantsResponse, kind)

    async def createTenant(self, req: m.CreateTenantRequest, kind: str = "proto") -> m.CreateTenantResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/CreateTenant", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.CreateTenantResponse, kind)

    async def updateTenant(self, req: m.UpdateTenantRequest, kind: str = "proto") -> m.UpdateTenantResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/UpdateTenant", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.UpdateTenantResponse, kind)

    async def deleteTenant(self, req: m.DeleteTenantRequest, kind: str = "proto") -> m.DeleteTenantResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/DeleteTenant", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.DeleteTenantResponse, kind)

    async def issueTenantToken(self, req: m.IssueTenantTokenRequest, kind: str = "proto") -> m.IssueTenantTokenResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/IssueTenantToken", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.IssueTenantTokenResponse, kind)

    async def listTenantTokens(self, req: m.ListTenantTokensRequest, kind: str = "proto") -> m.ListTenantTokensResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/ListTenantTokens", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListTenantTokensResponse, kind)

    async def revokeTenantToken(self, req: m.RevokeTenantTokenRequest, kind: str = "proto") -> m.RevokeTenantTokenResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/RevokeTenantToken", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.RevokeTenantTokenResponse, kind)

    async def rotateTenantToken(self, req: m.RotateTenantTokenRequest, kind: str = "proto") -> m.RotateTenantTokenResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/agent.v1.AdminService/RotateTenantToken", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.RotateTenantTokenResponse, kind)
